# Generated by Django 2.0.4 on 2018-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
